name: Build and publish
on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  deploy-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Build
        run: |
          poetry build -v
          poetry install --only-root
      - name: Check
        run: poetry run python -c "import cshogi"
      - name: Publish
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
  deploy-manylinux2010:
    runs-on: ubuntu-20.04
    env:
      CC: g++
      CXX: g++
    strategy:
      matrix:
        python-version: ["cp36-cp36m", "cp37-cp37m", "cp38-cp38", "cp39-cp39"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Build
        run: |
          poetry build -f sdist
          tar zvxf ./dist/*.tar.gz -C ./dist
          cp $(find ./dist -name setup.py) .
          export PYTHON_BIN="/opt/python/${{ matrix.python-version }}/bin"
          docker run --rm -v $(pwd):/work \
            -w /work quay.io/pypa/manylinux2010_x86_64 \
            /bin/sh -c "\
              $PYTHON_BIN/pip install numpy==1.19.5 Cython && \
              $PYTHON_BIN/python setup.py bdist_wheel && \
              cd dist && auditwheel repair *.whl"
      - name: Publish
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/wheelhouse/*
  deploy-manylinux_2_24:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["cp310-cp310", "cp311-cp311", "cp312-cp312"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Build
        run: |
          poetry build -f sdist
          tar zvxf ./dist/*.tar.gz -C ./dist
          cp $(find ./dist -name setup.py) .
          export PYTHON_BIN="/opt/python/${{ matrix.python-version }}/bin"
          docker run --rm -v $(pwd):/work \
            -w /work quay.io/pypa/manylinux_2_24_x86_64 \
            /bin/sh -c "\
              $PYTHON_BIN/pip install numpy Cython && \
              $PYTHON_BIN/python setup.py bdist_wheel && \
              cd dist && auditwheel repair *.whl"
      - name: Publish
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/wheelhouse/*
